name: Schedueld Push

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  send_failure_email:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
      - name: Send email with failure artifacts
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com 
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Playwright Tests Failed"
          body: "Playwright tests failed in branch ${{ github.ref_name }}. Check failure logs in attachment."
          to: ${{ secrets.EMAIL_USERNAME }}
          from: "GitHub Actions ${{ secrets.EMAIL_USERNAME }}"
          attachments: |
            playwright-report/test-results/test-report.html